storageClass:
  enable: true
 
ingressNginx:
  enable: true
  createNamespace: true
  
externalSecrets:
  enable: false
  createNamespace: false
  
tekton:
  enable: false
  createNamespace: false
  
keycloakPostgresql:
  enable: true
  createNamespace: true

keycloak:
  enable: true
  createNamespace: true

edp:
  enable: false
  createNamespace: false

argocd:
  enable: false
  createNamespace: false
  
defectdojo:
  enable: false
  createNamespace: false

karpenter:
  enable: true
  createNamespace: true
