# Storage Class
storageClass:
  enable: true
 
ingressNginx:
  enable: true
  createNamespace: true
  
externalSecrets:
  enable: true
  createNamespace: true
  
tekton:
  enable: true
  createNamespace: true
  
keycloakPostgresql:
  enable: true
  createNamespace: true
