apiVersion: v2
description: A Helm chart for EDP Install
home: https://epam.github.io/edp-install/
name: edp-install
type: application
version: 3.2.2
appVersion: 3.2.2


dependencies:
- name: edp-install
  version: 3.2.2
  repository: https://epam.github.io/edp-helm-charts/stable
