apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defectdojo-rabbitmq-specific
  namespace: edp-mm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: rabbitmq-password
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: defectdojo-rabbitmq-specific.rabbitmq-password
  - secretKey: rabbitmq-erlang-cookie
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: defectdojo-rabbitmq-specific.rabbitmq-erlang-cookie
