apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defectdojo-postgresql-specific
  namespace: edp-mm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstor
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: defectdojo-postgresql-specific.postgresql-password
  - secretKey: postgresql-postgres-password
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: defectdojo-postgresql-specific.postgresql-postgres-password
