{{- if and (.Values.edp) (.Values.edp.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edp-mm
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: edp-mm
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.edp.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  source:
    repoURL: https://epam.github.io/edp-helm-charts/stable
    chart: edp-install
    targetRevision: {{ .Values.edp.targetRevision }}
    helm:
      values: |
        edp:
        {{- toYaml .Values.edp | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: security
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.edp.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}