apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD Install

version: 5.33.2

appVersion: "v2.7.2"

dependencies:
- name: argo-cd
  version: 5.33.2
  repository: https://argoproj.github.io/argo-helm
