apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: username
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: keycloak-admin-creds.username
  - secretKey: password
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: keycloak-admin-creds.password
