apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameterstore
  namespace: security
spec:
  provider:
    aws:
      service: aws-parameterstore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecrets-aws
