apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github
  namespace: edp-mm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: argocd-github.sshPrivateKey
      decodingStrategy: Base64
  - secretKey: url
    remoteRef:
      key: /edp/mm-deploy-secrets
      property: argocd-github.url
  target:
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
